preload = /home/mario/Pictures/wallpapers/All_wallpapers_to_use/Reze.jpg

wallpaper {
    monitor = 
    path = /home/mario/Pictures/wallpapers/All_wallpapers_to_use/Reze.jpg
    fit_mode = cover
}

splash = false
